# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - run:
          name: Configure Bundler - use the same bundler version used in Gemfile.lock
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            sudo gem update --no-document --system
            gem install bundler --no-document -v "$BUNDLER_VERSION"
      - run:
          name: Clone repo and checkout branch
          command: |
            git clone https://github.com/mawilmouth/rails_tasker.git ~/src
            cd ~/src
            git fetch origin << pipeline.git.branch >>
            git checkout << pipeline.git.branch >>
      - run:
          name: Bundle Install
          command: cd ~/src && bundle install
      - run:
          name: RSpec
          command: cd ~/src && bundle exec rspec -- ~/src/spec

workflows:
  build-workflow:
    jobs:
      - build
